language: python
sudo: false
cache: pip
dist: xenial
python:
  - nightly
  - 3.7
  - 3.6
  - 3.5
install:
  - pip install --upgrade pip
  - pip install --upgrade --pre -r test-requirements.txt .
  - pip freeze
env:
  OAUTH2_TOKEN_URL="token_url"
  OAUTH2_USERDATA_URL="userdata_url"
script:
  - |
    if [[ "$TEST_LINT" = 1 ]]; then
      flake8 oauthenticator
    else
      py.test --cov oauthenticator oauthenticator
    fi
after_success:
  - codecov

matrix:
  include:
    - python: 3.7
      env: TEST_LINT=1
